/****** Object:  Database [widgetdbsitedb]    Script Date: 12/1/2019 8:21:13 PM ******/
CREATE DATABASE [widgetdbsitedb]  (EDITION = 'Basic', SERVICE_OBJECTIVE = 'Basic', MAXSIZE = 2 GB) WITH CATALOG_COLLATION = SQL_Latin1_General_CP1_CI_AS;
GO
ALTER DATABASE [widgetdbsitedb] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [widgetdbsitedb] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [widgetdbsitedb] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [widgetdbsitedb] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [widgetdbsitedb] SET ARITHABORT OFF 
GO
ALTER DATABASE [widgetdbsitedb] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [widgetdbsitedb] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [widgetdbsitedb] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [widgetdbsitedb] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [widgetdbsitedb] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [widgetdbsitedb] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [widgetdbsitedb] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [widgetdbsitedb] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [widgetdbsitedb] SET ALLOW_SNAPSHOT_ISOLATION ON 
GO
ALTER DATABASE [widgetdbsitedb] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [widgetdbsitedb] SET READ_COMMITTED_SNAPSHOT ON 
GO
ALTER DATABASE [widgetdbsitedb] SET  MULTI_USER 
GO
ALTER DATABASE [widgetdbsitedb] SET ENCRYPTION ON
GO
ALTER DATABASE [widgetdbsitedb] SET QUERY_STORE = ON
GO
ALTER DATABASE [widgetdbsitedb] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 7), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 10, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO)
GO
/****** Object:  Table [dbo].[Customer]    Script Date: 12/1/2019 8:21:13 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Customer](
	[CustomerId] [int] IDENTITY(1,1) NOT NULL,
	[FirstName] [nvarchar](50) NOT NULL,
	[LastName] [nvarchar](50) NOT NULL,
	[BirthMonth] [int] NOT NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CustomerLookup]    Script Date: 12/1/2019 8:21:13 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CustomerLookup](
	[customerId] [int] NOT NULL,
	[oAuthId] [int] NOT NULL,
	[userId] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[customerId] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER DATABASE [widgetdbsitedb] SET  READ_WRITE 
GO
